version: '${project.version}'
jdbcUri: 'jdbc:h2:./plugins/CartJets/cartjets'
maxSpeed: 1.0
vectorMultiplier: 0.75
taskRepeatingDelayInTicks: 20
# Updater config
updater:
  enabled: true
  downloadToPluginUpdateFolder: true
  targetUrl: 'https://github.com/joestrhq/CartJets/releases/latest/download/'
  pomPropertiesFile: 'pom.properties'
  classifier: 'shaded'