version: '${project.version}'
jdbcUri: 'jdbc:h2:./plugins/CartJets/cartjets'
maxSpeed: 1.0
vectorMultiplier: 1.25
taskRepeatingDelayInTicks: 20
# Jenkins updater config
jenkinsUpdater:
  mode: 'RELEASES'
  autoUpdate: true
  rootUrl: 'https://ci.joestr.at/job/CartJets/lastSuccessfulBuild/artifact/target/maven-archiver/'
  pomProperties: 'pom.properties'
  classifier: 'shaded'