version: '${project.version}'
jdbcUri: 'jdbc:h2:./plugins/CartJets/cartjets'
maxSpeed: 1.0
vectorMultiplier: 1.25
taskRepeatingDelayInTicks: 20
# Jenkins updater config
jenkinsUpdater:
  enabled: true
  downloadToPluginUpdateFolder: true
  targetUrl: 'https://ci.joestr.at/job/github.com_joestr/job/CartJets-develop/lastSuccessfulBuild/artifact/target/'
  pomPropertiesFile: 'maven-archiver/pom.properties'
  classifier: 'shaded'